version: '3.8'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: quickapps-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
    networks:
      - quickapps-network

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: quickapps-db
    ports:
      - "3306:3306"
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-quickapps}
      MYSQL_USER: ${MYSQL_USER:-quickapps}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-quickapps123}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - quickapps-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quickapps-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-quickapps}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-quickapps123}
    depends_on:
      - db
    networks:
      - quickapps-network

volumes:
  db-data:

networks:
  quickapps-network:
    driver: bridge